---
title: "Overview"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

SoilID Algorithm Testing
There are two forms of code testing:

1.	Code error testing: Testing for coding errors, i.e., does it run with all possible combination of inputs
2.	Code validation: Validation of the matching algorithm, i.e., how accurate is it.

Stage 1: Code error testing – ensure proper functioning of code given diversity of input data

1.	soilIDlist
    a.	Random sample
        i.	US: 3,000 random locations generated across US, 500 of which are in NOTCOM areas (i.e., areas without SSURGO coverage and infilled with STATSGO)
        ii.	Global: 3,000 random locations generated across globe excluding the US and its territories.

2.	soilIDrank
    a.	Random sample (US & Global)
        i.	Test random points using a dummy dataset that contains different degrees of data completeness.
        
            1.	All data
            2.	Slope only (US testing)
            3.	All data - only surface depth (i.e., 1-10)
            4.	All data - only sub-surface depth (i.e., 20-50)
            5.  Subset of properties (500 sample random subset)
                + Texture only
                + all depths
                + only surface depth (i.e., 0-1)
                + only sub-surface depth (i.e., 20-50)
                + Rock frags
                + all depths
                + only surface depth (i.e., 0-1)
                + only sub-surface depth (i.e., 20-50)
                + Color
                + all depths
                + only surface depth (i.e., 0-1)
                + only sub-surface depth (i.e., 20-50)  
            6.  Mix of properties and depths
                + Texture surface depth (i.e., 0-1) only, color sub-surface depth (i.e., 20-50) only
                + Color surface depth (i.e., 0-1) only, rock fragments sub-surface depth (i.e., 20-50) only
            7.  Cracking test dataset (US and Global points where vertisols are found)
                + All data with user identified clay and cracking
                + All data without user identified clay or cracking
                + All data - cracking only
                + All data - user clay only
                + Cracking only - not texture information
                + Texture w/ user clay but cracking not specified


